---
# This playbook distributes keys to hosts

- name: copy key
  hosts: all
  remote_user: root
  #become: true
  tasks:
  - name: create .ssh
    file: path=/root/.ssh state=directory
  - name: distribute key
    copy: src=/home/madgin/.ssh/kolla_public_keys dest=/root/.ssh/authorized_keys

